#pragma config(UART_Usage, UART1, uartUserControl, baudRate9600, IOPins, None, None)
#pragma config(Motor,  port1,            ,             tmotorVex393_HBridge, openLoop)
#pragma config(Motor,  port10,           ,             tmotorVex393_HBridge, openLoop)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//
task main()
{
  writeDebugStreamLine("Test");
  signed char motor1Power=0, motor2Power=0;
  while(true){
    motor1Power = getChar(UART1);
    motor2Power = getChar(UART1);
    writeDebugStreamLine("%d, %d",motor1Power, motor2Power);
    if (motor1Power != -1 && motor2Power != -1){
    	/* port1 must always be negative, or the directions will be wrong.*/
      motor[port1] =  -(motor1Power);
      motor[port10] = motor2Power;
    }
    delay(250);
  }
}
